### PR TITLE
feat: new CTA variant

### PR DESCRIPTION
**Pull request by omBratteng**
I forgot, but I think this is all that's needed on API side to add new CTA variant 😅 

AS-396

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Looks about right yes.
Nothing in the endpoint that validates based on graphQL? (we probably use toGraphEnum so it's fine)

**Comment by omBratteng** [comment]
> Nothing in the endpoint that validates based on graphQL? (we probably use toGraphEnum so it's fine)

We don't use it there at all, there's just a mutation and the mutation just takes the campaignId.

**Comment by rebelchris** [comment]
@omBratteng But what about the one that adds them to the DB?

**Comment by omBratteng** [comment]
> @omBratteng But what about the one that adds them to the DB?

@rebelchris I've added the new CTA to the retool app. And from CIO it just uses campaignId and userId. Nothing about the variant. So we should be good to go.

**Pull request merged**
