### PR TITLE
feat: add userState.vote for companion boot

### PR DESCRIPTION
**Pull request by capJavert**
Companion was missing `userState.vote` to be able to use new vote state. In scope of changes for engagement loop.

https://github.com/dailydotdev/apps/pull/2164

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]

**Review by DragosIorgulescu — APPROVED** [review]
no comment on the code itself, looks good 👌 I just wanted to recommend linking PRs together when they are related, makes it easier to connect the dots when reviewing or looking back.

**Comment by capJavert** [comment]
@DragosIorgulescu ah I usually do, missed it yesterday. Updated!

**Review by rebelchris — APPROVED** [review]

**Review by idoshamun — APPROVED** [review]

**Comment by sshanzel** [comment]
Maybe we should utilize our post by id fragment here to never forget anything in the future.

**Comment by capJavert** [comment]
We don't have fragments available in the API so merging this now. Boot should be slim either way.

**Pull request merged**
