### PR TITLE
feat: install infra dependencies since needed during build

### PR DESCRIPTION
**Pull request by capJavert**
Fixes build crashing after we found hotfix for dead letter https://app.circleci.com/pipelines/github/dailydotdev/daily-api/5966/workflows/23d84678-b5ab-44d9-8afe-ce317d93cf5c/jobs/23325

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]

**Comment by idoshamun** [comment]
initPubSub is no longer used anywhere. I don't think we need this additional step in the ci pipeline. We install the deps only when using pulumi

**Comment by omBratteng** [comment]
So @capJavert can instead remove that file and mention of it in package.json (`"cloud:init": "ts-node bin/initPubsub.ts",`) (and remove infra deps installation), that will™️ fix the issue.

**Comment by capJavert** [comment]
Even better to remove some code 🚀

**Comment by omBratteng** [comment]
It worked™️

**Pull request merged**
