### PR TITLE
feat: disable post export to tb

### PR DESCRIPTION
**Pull request by vpol**

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]

**Comment by omBratteng** [comment]
Right, this is still going to exist in k8s right? Haven't gotten round to looking into that pulumi issue

**Comment by vpol** [comment]
> Right, this is still going to exist in k8s right? Haven't gotten round to looking into that pulumi issue

from what I understand it's going to remove cron job from pulumi/k8s. this is all I need.

**Comment by vpol** [comment]
Screenshot 2024-07-05 at 16 41 14

@omBratteng

**Comment by omBratteng** [comment]
👍

**Pull request merged**
