### PR TITLE
fix: fix duplicate authors for featured comments

### PR DESCRIPTION
**Pull request by rebelchris**
Fixed the duplicate authors for featured comments.

Screenshot 2021-11-16 at 11 46 18
Screenshot 2021-11-16 at 11 46 24
Screenshot 2021-11-16 at 11 45 37
Screenshot 2021-11-16 at 11 45 48

Note: We need the " quotes hence the force backticks.

DD-307 #done

### CODE REVIEW

**Review by sshanzel — APPROVED** [review]
It is always so nice to see single-line fixes!

**Comment by idoshamun** [comment]
I thought it would be better to fix it at the root cause:
https://github.com/dailydotdev/daily-api/blob/master/src/cron/updateFeaturedComments.ts

What do you think?

**Comment by rebelchris** [comment]
@idoshamun Good point, I can fix it there for future reference, but guess we either have to manually run a fix query for legacy comments or keep this current fix as well?

What would you prefer?

**Comment by idoshamun** [comment]
@rebelchris we can keep the existing situation as is or create a migration file that fixes it. Whatever you think is a better solution

**Comment by rebelchris** [comment]
Hmm I think this fallback adds a nice net so would suggest we leave it now.

**Review by idoshamun — CHANGES_REQUESTED** [review]
I suggest adding a test case for `updateFeaturedComments` to test this fix

**Review by idoshamun — CHANGES_REQUESTED** [review]
I suggest adding a test case for `updateFeaturedComments` to test this fix

**Comment by rebelchris** [comment]
@idoshamun Good point!

Modified the test to check for this.

- Added `c7` which is the same user as `c2`.
- Ran the old version see result below (as expected)
- Now the new version this test succeeds

Screenshot 2021-11-17 at 09 53 31

**Review by idoshamun — APPROVED** [review]
LGTM!

**Pull request merged**
