### PR TITLE
fix: cleanup of unused CDC topic

### PR DESCRIPTION
**Pull request by rebelchris**
We had a unused topic that publishes messages [without](https://console.cloud.google.com/cloudpubsub/topic/detail/alerts-updated?hl=en&project=devkit-prod&tab=subscriptions) any subscribers.
It spooled up the CDC worker a lot with manually updating 50K alerts.

WT-1979 #done

### CODE REVIEW

**Review by capJavert — APPROVED** [review]
Looking good 👌

**Review by DragosIorgulescu — APPROVED** [review]
Code deletion PRs are my favorite kind of PRs 👌

**Review by sshanzel — APPROVED** [review]
Nice work! Do we maybe need to run an update on the tables' replica identity?

**Review by omBratteng — APPROVED** [review]

**Comment by rebelchris** [comment]
@sshanzel // @idoshamun good point! added that now

**Review by idoshamun — APPROVED** [review]

**Comment by idoshamun** [comment]
@rebelchris once merged and deployed remember to delete the topic from the streams repo

**Pull request merged**
