### PR TITLE
infra: bump pulumi common to use spot nodes

### PR DESCRIPTION
**Pull request by idoshamun**

### CODE REVIEW

**Comment by idoshamun** [comment]
@omBratteng this will move debezium to a spot node. any objections?

**Comment by omBratteng** [comment]
> @omBratteng this will move debezium to a spot node. any objections?

@idoshamun debezium is still running on old nodes because of the disk, I'm in the progress of moving them over to new nodes. Then we can move them to new nodes

**Comment by idoshamun** [comment]
@omBratteng oh so we can't do this update yet. but why is the disk a blocker? it's external to gke

**Review by omBratteng — APPROVED** [review]
Should be possible to merge this, the debezium instances have a `nodeSelector` on them, so they'll still be scheduled onto the old nodes

**Review by rebelchris — APPROVED** [review]

**Pull request merged**
