### PR TITLE
fix: replace profile fallback image

### PR DESCRIPTION
**Pull request by omBratteng**
<table>
 <tr>
  <td>Old
  <td>New
 <tr>
  <td>
  <td>
</table>

The migration will affect 87756 rows

AS-389

### CODE REVIEW

**Review by idoshamun — COMMENTED** [review]
That's gonna trigger hell lot of cdc messages so we have to deal with care. Should we consider not to update existing users?

**Comment by omBratteng** [comment]
> That's gonna trigger hell lot of cdc messages so we have to deal with care. Should we consider not to update existing users?

YOLO? 😈

**Comment by idoshamun** [comment]
it's better to merge in low time if you want to proceed with that

**Review by rebelchris — APPROVED** [review]
We should really consider just setting it null and having the app itself do fallback 😂
That makes it way easier to switch.

Also happy to migrate this as a single query (think in the past we used to be able to disable CDC temporary somehow right @idoshamun ?)

**Comment by idoshamun** [comment]
Having profile image as null has more implications than this. We will need to make sure we support it everywhere, otherwise things will start break. If we want to fix it as part of this scope we can do it, but it's more work

**Comment by omBratteng** [comment]
I could remove the migration and run it directly, but in batches to a few thousand to not overwhelm CDC?

**Comment by idoshamun** [comment]
sounds ok!

**Review by idoshamun — APPROVED** [review]

**Review by rebelchris — APPROVED** [review]

**Pull request merged**
