### PR TITLE
feat: added a profile picture redirector

### PR DESCRIPTION
**Pull request by rebelchris**
Added a public redirector endpoint where based on `userId` you can get redirected to user's profile image.

Usage as:
```
api.local.com/{userId}/profile-image
```

it will fallback to the placeholder image if user doesn't exist or has no image set in DB.

### CODE REVIEW

**Review by omBratteng — APPROVED** [review]

**Review by capJavert — APPROVED** [review]
Looks good!

For what do we/want to use this for?

Also not sure for fastify, which status code 3xx is default for redirect, we probably want 307 temp since user can change profile picture.

**Comment by rebelchris** [comment]
@capJavert The default is 302 which also indicates it's [temporary](https://www.baeldung.com/cs/redirection-status-codes#302-redirection).
Is that alright?

**Comment by capJavert** [comment]
Yeah, fine as well in this case 👍

**Review by idoshamun — APPROVED** [review]
Nice!

**Pull request merged**
