### PR TITLE
feat: unknown source

### PR DESCRIPTION
**Pull request by sshanzel**
Introducing new source for the private links.

Note: merging is blocked until the correct image source link is provided by the design/product team.

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
Since its private maybe just default it to a placeholder image or null if we allow it.
We will render it differently on FE most likely but also happy to wait for designs answer.

**Comment by sshanzel** [comment]
@rebelchris yes, I was thinking if we have a placeholder image for `source` but I couldn't remember any, so I reached out to product/design team.

**Comment by sshanzel** [comment]
> @sshanzel we also need to add this source to our seed files

It would conflict with our local environment, I think. Once the migration is finished, there will already be an entity for `unknown` so once we try to run the seeds with `unknown`, it will crash. I think this should be good like the way we did for keywords (iirc).

**Comment by idoshamun** [comment]
@sshanzel you're right. My bad

**Comment by sshanzel** [comment]
Would love to hear what you think 🚢

**Review by idoshamun — APPROVED** [review]
Awesome!

**Review by rebelchris — APPROVED** [review]
Nice work!

**Pull request merged**
