### PR TITLE
feat: add db:seed:upsert npm script

### PR DESCRIPTION
**Pull request by kopancek**
Adds `--upsert` option to `import.ts` script and new npm script `db:seed:upsert`.

This allows the import script to try to upsert all of the seeds, even if there are errors/duplicates on some of the insert calls. In case there's a conflict, it updates the row instead.

Without this option the script fails on the first error/duplicate row it finds and never inserts the rest of the entities.

### CODE REVIEW

**Review by idoshamun — APPROVED** [review]
💪

**Review by capJavert — COMMENTED** [review]
In which case is this needed, only when you already have some data in the db?

**Comment by kopancek** [comment]
> In which case is this needed, only when you already have some data in the db?

Yes, exactly. But I figured out how to do upsert properly, so will update this PR...

**Review by capJavert — COMMENTED** [review]
To me personally this seems like too much logic for little gains, its a rare case where you actually need to keep local data and also when we modify the seed. It is easier to just do a schema reset with `db:migrate:reset` and then seed again. 

Maybe as alternative would just `repository.save` be a better option if we want to support the multiple calls of seed?

**Comment by rebelchris** [comment]
I personally also prefer to simply redo the seed all together.

**Comment by kopancek** [comment]
> To me personally this seems like too much logic for little gains 🙏 , its a rare case where you actually need to keep local data and also when we modify the seed. It is easier to just do a schema reset with `db:migrate:reset` and then seed again.
> 
> Maybe as alternative would just `repository.save` be a better option if we want to support the multiple calls of seed?

I don't know, I find it quite useful for local development to keep the test data intact and just seed new things. Especially if someone else upgraded the DB schema or seeds and I don't really care about those changes, just want everything to work nicely.

It also already happened to me more than once that I ran the import seed script and it failed with an error and I didn't understand how to reset the DB state.

If we decide to scrap this, at least I now know that `db:migrate:reset` resets the DB. And I know how to work with `upsert` from typeorm, so learned something 😊

**Comment by capJavert** [comment]
> It also already happened to me more than once that I ran the import seed script and it failed with an error and I didn't understand how to reset the DB state.

yeah sorry for that, this was due to bug that was fixed https://github.com/dailydotdev/daily-api/commit/b682d04feacf628b00661883e4a7aa7524215044, now seed will go through

**Review by sshanzel — APPROVED** [review]
Since it is in a separate command, I am cool with it as it has proven beneficial to some. However, personally, I would probably be sticking with the original commands to do a clean slate whenever I want to import data.

**Review by nensidosari — APPROVED** [review]
Should we merge or close this PR? It would be good if we would just take a decision.
Personally I think since it improves lives for some people, and has no downsides, why not have it?

**Review by idoshamun — APPROVED** [review]

**Pull request closed without merging**
