### PR TITLE
fix: remove `user_marketing_cta` table from debezium as we do not listen to those changes anymore

### PR DESCRIPTION
**Pull request by omBratteng**

### CODE REVIEW

**Review by capJavert — APPROVED** [review]

**Review by idoshamun — COMMENTED** [review]
Won't it impact the cache?

**Review by idoshamun — APPROVED** [review]

**Review by rebelchris — APPROVED** [review]
When did we listen to this?

**Comment by omBratteng** [comment]
Before we got the CIO integration

**Comment by omBratteng** [comment]
https://github.com/dailydotdev/daily-api/blob/3a59ac30d5fcb2fcd797a4ee3e8e7f33ff9c3fa7/src/workers/cdc/primary.ts#L872-L874

**Pull request merged**
