### PR TITLE
feat: notification email preference

### PR DESCRIPTION
**Pull request by sshanzel**
As discussed, to keep things simple, we will include the notification email preference in the user's table than creating a new one.

We will then create a separate table once we decide to implement a more granular control of the notification preference.

### CODE REVIEW

**Review by idoshamun — CHANGES_REQUESTED** [review]
Looks perfect! One change I'd like to ask is to respect the new field in the email sending worker. So if it's false we will not send any notification email

**Review by rebelchris — APPROVED** [review]
Nothing besides Ido's comment

**Review by el — APPROVED** [review]
LGTM, maybe we can improve the naming of the field from `notificationEmail` to `notifyByEmail` but not necessary

**Comment by sshanzel** [comment]
@idoshamun I have also added a test to ensure the worker won't send any email in case the user preferred not to receive them.

**Comment by sshanzel** [comment]
> LGTM, maybe we can improve the naming of the field from `notificationEmail` to `notifyByEmail` but not a blocker

@el good point. We have a plan in the future to make a separate table for the notifications preferences, we can probably apply the suggestion in the next phase. WDYT?

**Pull request merged**
