### PR TITLE
fix: banned or deleted post should not be in history

### PR DESCRIPTION
**Pull request by sshanzel**
DD-528

This fixes the banned and deleted posts being shown in the user's history.

### CODE REVIEW

**Review by idoshamun — CHANGES_REQUESTED** [review]
Looks great! The only comment is that banned posts should be kept in the reading history. We need to remove only the deleted ones

**Comment by sshanzel** [comment]
Woop! Woop! Updated the query now. Thank you! 🙇  @idoshamun

**Review by rebelchris — APPROVED** [review]
Nice one!

**Review by idoshamun — APPROVED** [review]
Yes!!!

**Pull request merged**
