### PR TITLE
fix: add index optimization

### PR DESCRIPTION
**Pull request by rebelchris**
We had another missed index on the source images.

Screenshot 2023-10-04 at 13 48 11

### CODE REVIEW

**Review by capJavert — COMMENTED** [review]
We should add it to typeorm entity and then from that auto generate migration?

**Comment by rebelchris** [comment]
@capJavert good point, added :)

**Comment by idoshamun** [comment]
@rebelchris where do we use this query? It looks pretty weird to me

**Comment by rebelchris** [comment]
@idoshamun It's the devcard query for sources
Screenshot 2023-10-04 at 14 48 40

**Review by idoshamun — APPROVED** [review]
Thanks a lot for showing me the query!
We'll need to optimize devcard in the future

**Pull request merged**
