### PR TITLE
feat: use text instead of boolean cast index

### PR DESCRIPTION
**Pull request by capJavert**
After deployment of https://github.com/dailydotdev/daily-api/pull/1504 I noticed that onboarding tags were still slow. 

After further debugging I found out why the query is slow. It was not due to index (I mean they help) but the main culprit is how typeorm assembles the query when you use json fields, I logged it under the hood and the query is something like:
```sql
SELECT value FROM keyword WHERE flags = '{ "onboarding": true }' ORDER BY value ASC
```
With the above query we don't actually hit the index since query queries the whole flags field. Optimal query (and what I was expecting `typeorm` was doing) would be:

```sql
SELECT value FROM keyword WHERE (flags->'onboarding') = 'true' ORDER BY value ASC
```

After replacing inefficient query from `typeorm` with the raw one it actually worked and query was much faster.

After adjusting the query I tried the actual query on psql version that was same as production and noticed that index was not used and query was slow again, `EXPLAIN` was saying that it did not use the index:
image

Locally on psql v15 it used it:
image

After some additional debugging with Ido we noticed that on our prod version (psql v11) the index was working only if we used plain text index for json field instead of boolean. So in this PR we add migration to add the plain index.

On general note until we upgrade our psql version we have to make sure we use raw queries when querying per `flags` json columns.

### CODE REVIEW

**Comment by capJavert** [comment]
@rebelchris Ido mentioned if you can prioritize checking the existing implementations against this same issue, from my quick check:
- `source_member` table has a multi column index for `flags` that needs to be replaced with plain one
- we have some `find` and `findBy` queries targeting JSON fields which are probably not as efficient because of how typeorm assembles them, they need to be replace with raw ones
- I think we mostly did not see this before because other tables using `flags` are not as big as `keyword` table

**Review by rebelchris — APPROVED** [review]
Interesting, thanks for noticing this and doling the extensive research and testing.
Added a ticket for next week :)

**Review by idoshamun — APPROVED** [review]

**Review by omBratteng — APPROVED** [review]

**Review by DragosIorgulescu — APPROVED** [review]
always had a love/hate relationship with ORMs (mostly hate), nice work 🚀

**Comment by capJavert** [comment]
@idoshamun just let me know when you manage to remove the index we added.

**Comment by idoshamun** [comment]
@capJavert I'll do it tomorrow, but that shouldn't block this

**Comment by capJavert** [comment]
@idoshamun I just merge this? Was worried that index delete will hang.

**Comment by idoshamun** [comment]
@capJavert closely monitor the deployment. Let me know if it goes south

**Pull request merged**
