### PR TITLE
chore: stop running unnecessary commands

### PR DESCRIPTION
**Pull request by sshanzel**
I noticed our test runners are executing the `completedUserActions` file.

Screenshot 2023-05-16 at 11 31 49 PM

### CODE REVIEW

**Review by idoshamun — COMMENTED** [review]
Is this the right solution?
Basically it will make the script not work in case we want to run it.
Pretty sure there's another reason for that. Wdyt?

**Comment by rebelchris** [comment]
@idoshamun should we actually not simply remove them?
They should only have had this one use and it can only cause confusion down the line maybe?

**Comment by sshanzel** [comment]
> Pretty sure there's another reason for that. Wdyt?

I realized we have a dedicated test for it. Maybe we should actually delete those files as Chris suggested?

**Comment by idoshamun** [comment]
I usually tend to keep utility files but it's your call you can either remove them or disable their tests. I don't have strong opinion here

**Comment by sshanzel** [comment]
> I usually tend to keep utility files but it's your call you can either remove them or disable their tests. I don't have strong opinion here

Let's disable the test, when I created a new bin file, I referenced old implementations which can probably useful to new comers in the future.

**Review by idoshamun — APPROVED** [review]

**Review by rebelchris — APPROVED** [review]

**Pull request merged**
