### PR TITLE
fix: give the ghost user a ghostly username 👻

### PR DESCRIPTION
**Pull request by omBratteng**
<table>
<tr>
 <td>Before
 <td>
<tr>
 <td>After
 <td>
</table>

### CODE REVIEW

**Review by capJavert — COMMENTED** [review]
I think there was a [discussion before](https://dailydotdev.slack.com/archives/C03QZBF46JC/p1683629548726909) on how we should call the user so not sure this rename is needed. No strong feelings about it though but might want to align with product and everyone else.

**Comment by omBratteng** [comment]
There are ongoing [discussions here](https://dailydotdev.slack.com/archives/C02QDJFKUJ1/p1704951468237789), also raised the rename

**Comment by omBratteng** [comment]
Converted it to draft while we wait for readme copy and an updated avatar 👻

**Review by rebelchris — APPROVED** [review]
Cool, nothing blocking from my side.

**Review by idoshamun — APPROVED** [review]

**Pull request merged**
