### PR TITLE
fix: support sql escaping

### PR DESCRIPTION
**Pull request by idoshamun**
The previous implementation was sensitive to sql injections and escaping issues. I use parameterized query now to fix it

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]

**Comment by idoshamun** [comment]
@capJavert I don't like it either but TypeORM query builder for such queries is lacking. The part that is sensitive to injections would still need to be written as raw query.
The other option is to drop this optimization, and use multiple queries to achieve the same thing. I tried to make it work in one query. Essentially creating whatever doesn't exist and then fetch everything.
I can change it to two queries. As it's a background worker, I don't mind the performance so much. Would you prefer that?

Sidenote: I enabled auto merge (sorry 🙏 ), whatever we discuss and agree I can apply on a separate PR.

**Comment by rebelchris** [comment]
Hmm maybe the 2 separate using queryBuilder would be best then?

**Comment by capJavert** [comment]
@idoshamun yeah, no worries. Yes I would prefer 2 queries too. 👌

**Comment by idoshamun** [comment]
@capJavert @rebelchris coming right at ya

**Pull request merged**
