### PR TITLE
chore: minor package bumps

### PR DESCRIPTION
**Pull request by rebelchris**
Did some minor version bumps.

### CODE REVIEW

**Comment by rebelchris** [comment]
Decided to remove fastify bump due to build error.

```
node_modules/fastify/types/instance.d.ts:146:3 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

146   [Symbol.asyncDispose](): Promise<undefined>;
      ~~~~~~~~~~~~~~~~~~~~~

node_modules/fastify/types/instance.d.ts:146:11 - error TS2339: Property 'asyncDispose' does not exist on type 'SymbolConstructor'.

146   [Symbol.asyncDispose](): Promise<undefined>;
              ~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/fastify/types/instance.d.ts:146
```

**Comment by rebelchris** [comment]
Apparently they did add a eslint disable, will give it a try when they open the new release.

https://github.com/fastify/fastify/commit/24fffff11d26ed8ae0ab5ef7406e2233cc7e87b9

https://github.com/fastify/fastify/issues/5094#issuecomment-1763120779

**Review by idoshamun — APPROVED** [review]
Thanks 🙏

**Comment by rebelchris** [comment]
Actually team Fastify was super fast and solved it https://github.com/fastify/fastify/issues/5094
So now this is also updated

**Review by idoshamun — APPROVED** [review]

**Pull request merged**
