### PR TITLE
refactor: Settings Entity - openNewTab Column

### PR DESCRIPTION
**Pull request by sshanzel**
Hi Team,

Based on this [issue](https://github.com/dailydotdev/daily/issues/167), we will be implementing an "Open New Tab" functionality configured through the extension's settings but things shall also be developed on the API side.

Creating this draft PR for the discussed feature.

Thanks!

Best Regards,
Lee

### CODE REVIEW

**Comment by idoshamun** [comment]
The build fails because you forgot to generate a migration file for the new change.
Run the following: `npm run db:migrate:make -- OpenNewTabSetting`
This will create a new migration file that will take care of updating the db.
Other than that, thanks so much for the super quick PR 🔥

**Comment by sshanzel** [comment]
Thanks, man! I was wondering where I can pull off the migration for the changes in the `Entity`, thank you so much for mentioning!

**Comment by sshanzel** [comment]
Hi @idoshamun, do you have some ideas with regard to the image below? I've tried altering the rules based on some fixes I found in some similar issues.

image

**Comment by idoshamun** [comment]
Hmm did you format any of the files with your IDE?
If so make sure to run `npm run lint -- --fix` to automatically fix all the lint issues.
The master version has passed all the lint issues so it shouldn't be a problem unless you introduce new files that I'm not aware of.
By the way, before creating a migration file, you have to make sure that your local database is up-to-date with the schema.

**Comment by sshanzel** [comment]
> Hmm did you format any of the files with your IDE?
> If so make sure to run `npm run lint -- --fix` to automatically fix all the lint issues.
> The master version has passed all the lint issues so it shouldn't be a problem unless you introduce new files that I'm not aware of.
> By the way, before creating a migration file, you have to make sure that your local database is up-to-date with the schema.

I see. I was running `npm run lint --fix`, it was missing the 2 prior hyphens, now it fixed the concern with the EOL. My code editor's default was `CRLF`. Thank you for mentioning the right command!

**Comment by idoshamun** [comment]
Hi @sshanzel, need any help fixing the build?

**Comment by sshanzel** [comment]
> Hi @sshanzel, need any help fixing the build?

Hi Ido, As I saw from the logs, the test snapshots need to be updated, unfortunately, there's some issue on my environment and the test cases fail even fresh from pull. I am actually planning to figure the issue out this coming weekend as I believe my environment is the one causing it.

If you don't mind, can you please update the snapshots on your environment so we can see if the build will be successful since the changes I've made are quite straightforward and simple?

**Comment by idoshamun** [comment]
I've updated your branch with master and I'll check again the snapshots and see if I can solve it :)

**Comment by sshanzel** [comment]
Thank you so much Ido!

**Comment by idoshamun** [comment]
I found the issue! Your environment is perfect, it's just that you set `openNewTab` as a required field when updating the user settings. This broke the tests but now I fixed it. Probably we will have to update snapshots accordingly but you can do it locally as well.

**Comment by sshanzel** [comment]
Oh, that's why. Thanks, man! Guess this is ready for review!

**Comment by idoshamun** [comment]
Just make sure to update the snapshots so the tests may pass.

**Comment by sshanzel** [comment]
Will do it immediately when I arrived home. Thanks, Ido!

**Comment by idoshamun** [comment]
Something with your snapshot is not valid.
Please revert back your changes to the snapshot and just edit it manually according to here:
https://app.circleci.com/pipelines/github/dailydotdev/daily-api/386/workflows/c6d79783-9151-4492-8cbd-d4fc363a7486/jobs/979
It's only 2 changes

**Comment by sshanzel** [comment]
Hi @idoshamun, thank you for your patience as always! I think this is now ready for review as it has passed the tests after the manual modification of the snapshots. Best of luck!

**Pull request merged**
